image: ubuntu:latest

before_script:
  - apt update -yq
  - apt install -yq ca-certificates curl
  - echo "deb [trusted=yes] https://packages.twingate.com/apt/ /" | tee /etc/apt/sources.list.d/twingate.list
  - apt update -yq
  - apt install -yq twingate
  - echo "$TWINGATE_SERVICE_ACCOUNT" | base64 --decode | twingate setup --headless=-
  - twingate start

# Now you can access any Twingate resource which the service account has access to.
#test:
#  stage: test
#  script: |
#    # uncomment next line for debug
#    # cat /var/log/twingated.log
#    # test protected resource
#    curl -v -m 10 "http://10.0.0.1:80" > /dev/null