image: ubuntu:latest

before_script:
    - apt update -yq
    - apt install -yq ca-certificates curl

test:
  stage: build
  script: |
    # test protected resource
    curl -v -m 10 "http://172.30.2.229:3000" > /dev/null
    # test public resource
    curl -v -m 10 https://www.twingate.com > /dev/null